#exception-name error:

# try:
#     x=10/5
#     print11(x)
# except ValueError as error:
#     print12("Error:",error)